version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: player_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass

  player_service:
    build: ./atomic_services/player
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@mysql/player_db

  enemy_service:
    build: ./atomic_services/enemy
    ports:
      - "5005:5005"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@mysql/enemy_db

  inventory_service:
    build: ./atomic_services/inventory
    ports:
      - "5001:5001"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@mysql/inventory_db

  score_service:
    build: ./atomic_services/score
    ports:
      - "5015:5015"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@mysql/score_db

  activity_log_service:
    build: ./atomic_services/activity_log
    ports:
      - "5013:5013"
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@mysql/activity_log_db

  web_app:
    build: ./web
    ports:
      - "5050:5050"
    depends_on:
      - player_service
      - enemy_service
      - inventory_service
      - score_service
      - activity_log_service
