version: '3.8'

services:
  mysql:
    image: mysql:8
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: player_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpass

  player_service:
    build: ./atomic_services/player
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@mysql:3306/player_db
    ports:
      - "5000:5000"

  enemy_service:
    build: ./atomic_services/enemy
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@mysql:3306/enemy_db
    ports:
      - "5005:5005"

  inventory_service:
    build: ./atomic_services/inventory
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@mysql:3306/inventory_db
    ports:
      - "5001:5001"

  score_service:
    build: ./atomic_services/score
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@mysql:3306/score_db
    ports:
      - "5015:5015"

  activity_log_service:
    build: ./atomic_services/activity_log
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+mysqlconnector://user:password@mysql:3306/activity_log_db
    ports:
      - "5013:5013"

  web_app:
    build: ./web
    restart: always
    ports:
      - "5050:5050"
    depends_on:
      - player_service
      - enemy_service
      - inventory_service
      - score_service
      - activity_log_service
    environment:
      - SELECT_CHARACTER_URL=http://player_service:5000/select_character
      - ROOM_SERVICE_URL=http://entering_room:5011/room
      - COMBAT_SERVICE_URL=http://fight_enemy:5008/combat
