version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"      # RabbitMQ default port
      - "15672:15672"    # Management UI (optional, helpful for debugging)
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: main_db
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql

  player_service:
    build: ./atomic_services/player
    restart: always
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@mysql/player_db
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  character_service:
    build: ./atomic_services/character
    restart: always
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@mysql/character_db
    ports:
      - "5003:5003"
    depends_on:
      - mysql

  enemy_service:
    build: ./atomic_services/enemy
    restart: always
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@mysql/enemy_db
    ports:
      - "5005:5005"
    depends_on:
      - mysql

  item_service:
    build: ./atomic_services/item
    restart: always
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@mysql/item_db
    ports:
      - "5002:5002"
    depends_on:
      - mysql

  inventory_service:
    build: ./atomic_services/inventory
    restart: always
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@mysql/inventory_db
    ports:
      - "5001:5001"
    depends_on:
      - mysql

  dice_service:
    build: ./atomic_services/dice
    restart: always
    ports:
      - "5007:5007"

  score_service:
    build: ./atomic_services/score
    restart: always
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@mysql/score_db
    ports:
      - "5008:5008"
    depends_on:
      - mysql

  activity_log_service:
    build: ./atomic_services/activity_log
    restart: always
    environment:
      DATABASE_URL: mysql+mysqlconnector://user:password@mysql/activity_log_db
    ports:
      - "5013:5013"
    depends_on:
      - mysql
      - rabbitmq

  fight_enemy_service:
    build: ./composite_services/fight_enemy
    restart: always
    environment:
      PLAYER_SERVICE_URL: http://player_service:5000
      ENEMY_SERVICE_URL: http://enemy_service:5005
      DICE_SERVICE_URL: http://dice_service:5007
      ACTIVITY_LOG_SERVICE_URL: http://activity_log_service:5013
    ports:
      - "5009:5009"
    depends_on:
      - player_service
      - enemy_service
      - activity_log_service
      - dice_service

  entering_room_service:
    build: ./composite_services/entering_room
    restart: always
    environment:
      PLAYER_SERVICE_URL: http://player_service:5000
      ENEMY_SERVICE_URL: http://enemy_service:5005
      FIGHT_ENEMY_SERVICE_URL: http://fight_enemy_service:5008
      ITEM_SERVICE_URL: http://item_service:5002
      ACTIVITY_LOG_SERVICE_URL: http://activity_log_service:5013
    ports:
      - "5011:5011"
    depends_on:
      - player_service
      - enemy_service
      - fight_enemy_service
      - item_service
      - activity_log_service

  manage_game_service:
    build: ./composite_services/manage_game
    restart: always
    environment:
      PLAYER_SERVICE_URL: http://player_service:5000
      ENEMY_SERVICE_URL: http://enemy_service:5005
      ACTIVITY_LOG_SERVICE_URL: http://activity_log_service:5013
    ports:
      - "5014:5014"
    depends_on:
      - player_service
      - enemy_service
      - activity_log_service

  open_inventory_service:
    build: ./composite_services/open_inventory
    restart: always
    environment:
      INVENTORY_SERVICE_URL: http://inventory_service:5001
      ITEM_SERVICE_URL: http://item_service:5002
    ports:
      - "5010:5010"
    depends_on:
      - inventory_service
      - item_service

  calculate_score_service:
    build: ./composite_services/calculate_score
    restart: always
    environment:
      SCORE_SERVICE_URL: http://score_service:5008
    ports:
      - "5015:5015"
    depends_on:
      - score_service

  web_app:
    build: ./web
    restart: always
    ports:
      - "5050:5050"
    environment:
      PLAYER_SERVICE_URL: http://player_service:5000
      ENTERING_ROOM_SERVICE_URL: http://entering_room_service:5011
      FIGHT_ENEMY_SERVICE_URL: http://fight_enemy_service:5008
      INVENTORY_SERVICE_URL: http://open_inventory_service:5010
